### ISSUE TITLE
rxjs pipe? map?

### ISSUE THREAD

**Issue by tanjunior** [tanjunior/ionic3app#1]
![1](https://user-images.githubusercontent.com/11617693/36027191-2e374902-0dd5-11e8-8337-3640f1872232.png)

https://stackoverflow.com/questions/47198706/rxjs-pipe-and-lettable-operator-map-this-context-of-type-void-is-not-assi

![2](https://user-images.githubusercontent.com/11617693/36027198-34e4ddaa-0dd5-11e8-8870-69416a7d6146.png)

**Comment by surajrao** [comment]
change import of map to `import { map } from 'rxjs/operators/map';` to use pipeable operator (operator with an s). and also you are missing a return in that function. More https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

**Comment by tanjunior** [comment]
solved
